name: ci

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ ubuntu-latest ]
            build_type: [ Release ]

    steps:
        - uses: actions/checkout@v4

        - name: install deps
          run: sudo apt-get -y install cmake

        - name: create build dir
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: configure build
          run: |
            cmake .. \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}\
                -BBUILD_TESTS=ON
                
        - name: build
          run: cmake --build . --config ${{ matrix.build_type }}
        
        - name: test
          run: ./cdgnx-test